/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ymt_HelloWorld */

#ifndef _Included_com_ymt_HelloWorld
#define _Included_com_ymt_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ymt_HelloWorld
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ymt_HelloWorld_sayHello
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_ymt_HelloWorld
 * Method:    hello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ymt_HelloWorld_sayHello2
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
